### ISSUE TITLE
롬복 제대로 적용

### ISSUE THREAD

**Issue by ttkmw** [Nexters/netflix_backend#13]
아직 롬복에서 data만 쓰고 있고,

어떠어떠한 생성자를 만들어주는지 등 자세히 알지 못합니다.

좀 더 알아보고 잘 적용해보도록하겠습니다.

**Comment by ttkmw** [comment]
@inDlife

**Comment by kwongiho** [comment]
JPA + Lombok을 사용할 경우,
@ManyToOne, @OneToOne, @OneToMany 등 ,
조인매핑을 사용할경우 @ToString overflow 이슈가 있습니다

**Comment by ttkmw** [comment]
@KwonGiho
피드백 감사드립니다!^^
아직 코딩이 많이 안돼있지만, 좀 더 코딩 후 리뷰할 거리가 좀 생기면 코드리뷰도 해주시면 큰 도움 될 것 같습니다!ㅎㅎ
